services:
  app:
    image: node:22
    container_name: mitgliedsantrag_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:Z
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development